name: 'Aviator MergeQueue affected targets calculator for GitHub Actions workflows'
description: 'Calculate affected targets based on GitHub Actions workflows'
author: 'Aviator Technologies'

branding:
  icon: 'heart'
  color: 'red'

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  aviator-api-url:
    description: The Aviator pull_request API endpoint
    default: "https://api.aviator.co/api/v1/pull_request/"
    required: false
  aviator-token:
    description: The Aviator token for the Aviator API
    required: true

runs:
  using: node20
  main: dist/index.js
